// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBRtB3d1N-00RlCvNj9DHjE4lgEtvr_YQ',
    appId: '1:679637050237:web:3d08238401f02ed6226214',
    messagingSenderId: '679637050237',
    projectId: 'simple-login-instagram-ui',
    authDomain: 'simple-login-instagram-ui.firebaseapp.com',
    storageBucket: 'simple-login-instagram-ui.appspot.com',
    measurementId: 'G-TNRNTD7WCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZxFdlzWmU7AhGCnULr5pF7L68r_fw29c',
    appId: '1:679637050237:android:5dcc461f427d613a226214',
    messagingSenderId: '679637050237',
    projectId: 'simple-login-instagram-ui',
    storageBucket: 'simple-login-instagram-ui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIEYI97zKPAHJJaMJ2m7aX7JQIjyB9X2E',
    appId: '1:679637050237:ios:99c5c962727d99e4226214',
    messagingSenderId: '679637050237',
    projectId: 'simple-login-instagram-ui',
    storageBucket: 'simple-login-instagram-ui.appspot.com',
    iosClientId: '679637050237-eturrqqfe85tkte701bb5r7d6aodo38u.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginLogoutSimpleUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIEYI97zKPAHJJaMJ2m7aX7JQIjyB9X2E',
    appId: '1:679637050237:ios:99c5c962727d99e4226214',
    messagingSenderId: '679637050237',
    projectId: 'simple-login-instagram-ui',
    storageBucket: 'simple-login-instagram-ui.appspot.com',
    iosClientId: '679637050237-eturrqqfe85tkte701bb5r7d6aodo38u.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginLogoutSimpleUi',
  );
}
